### ISSUE TITLE
Speed not reported

### ISSUE THREAD

**Issue by piiskop** [gpx-animator/gpx-animator#345]
The final video has _0.0 km/h_ for the speed although the speed varies for running.

**Comment by McPringle** [comment]
All videos I know have a valid speed display. I need more information to reproduce your problem and track down the error. Can you please provide the saved configuration (File > Save as) together with the GPX file? You can upload it here to this issue or, if you prefer to keep it private, via email to support@gpx-animator.app (please add "Issue #345" to the subject).

**Comment by piiskop** [comment]
Github doesn't support the [configuration file](https://nextcloud.tennis24.ee/index.php/s/JM7j3z7aNcX67ct) type.

**Comment by piiskop** [comment]
Github doesn't support the [configuration file](https://nextcloud.tennis24.ee/index.php/s/JM7j3z7aNcX67ct) type.

**Comment by piiskop** [comment]
Github doesn't support [GPX-file](https://nextcloud.tennis24.ee/index.php/s/9g9TEPwn2gj3prQ) type.

**Comment by McPringle** [comment]
Create a ZIP file... ;-)

**Comment by piiskop** [comment]
I don't see why ZIP's are allowed and GPX's aren't. One has to zip and the other one has to unzip. I hate zipping-unzipping. Instead, I uploaded the file to my file sharing system for reusing and yes, you can just click the link in my previous post and download it from there.

**Comment by rneppi** [comment]
In my case there is also no proper speed displayed in video. We where hiking with 4 - 5 km/h, but in the movie 0,0 km/h, for short times 1,0 km/h, is shown.

**Comment by McPringle** [comment]
The GPX file contains entries with a description containing the text "Speed: 0 km/h". Example from your file:

```
<desc>Speed: 0 km/h
Elevation: 20 m</desc>
```

**Comment by piiskop** [comment]
These are the waypoints. i do not see any reason why a waypoint has to have speed as a characteristic. The track itself has no speed information. It has to be calculated according to timestamps and geographical coordinates.

My report was made almost two years ago and tonight, you had a look at this issue for the first time by investigating the source file. And you closed this issue as completed without having our confirmation.

Meanwhile, i am not using your software anymore as _Shotcut_ has a nice feature now for this purpose and it is working.
