### ISSUE TITLE
No GPS "signal" feature

### ISSUE THREAD

**Issue by szolnokit** [gpx-animator/gpx-animator#388]
Sometimes the moving stopped on video, but the time runnung.. And the watcher can't decide what happaned. Is the object stopped, or just no GSP signal?

It would be better, when any status visible (example: red dot, coordinate color change, etc) on the video when no coordinate at amount (adjustable) of time.

**Comment by szolnokit** [comment]
Added myself at pull #390

**Comment by szolnokit** [comment]
This is my first contributon on GitHub :) I hope I did everything well...

**Comment by McPringle** [comment]
Well done and sorry for my very long reply times. This year was really challenging. Version 1.8 of GPX Animator will be published soon and include your work!
