### ISSUE TITLE
New Feature: Different Icon at End of Each Track

### ISSUE THREAD

**Issue by HanSolo68** [gpx-animator/gpx-animator#403]
Currently the icon shown at the end of each track is the same as during e.g. driving.

it would be fine to define what icon shall be displayed at the end of the track, including none.

Benefit: use car for the track and e.g. A hut/tent for the overnight stay for travels (hut/tent as „end icon“).
Benefit: seemless transition from one track to the next (none as „end icon“)

**Comment by McPringle** [comment]
The feature to specify an optional end icon for each track is available since v1.8.0.
