### ISSUE TITLE
Unable to set track rendering order

### ISSUE THREAD

**Issue by thereticle** [gpx-animator/gpx-animator#419]
I have travelled a section of a longer route and I would like to show the longer route first and superimpose the piece I have done over it.
Unfortunately I have not found an option that allows me to select the order in which the two tracks are rendered. 
GPX animator always renders the shorter track first (which should be on top) and then the longer one. 
The final result is that the track that I have travelled eventually disappears below the other one.
Is there any way to sort the rendering of the two tracks?

**Comment by McPringle** [comment]
Hello @thereticle 

The order of rendering the tracks is calculated by the recording time of the track. All tracks of one rendering configuration are automatically synchronized. You have two options to change this:

1. Modify the date and time values in your GPX file(s).
2. Set the `time offset` of the track in GPX Animator.

For example, if you want to render a specific track first, subtract a few hours or days from the date of recording. Some, if you want to render a specific track last: Add a few hours or days.

This should solve your problem, so I close this issue. If not, please reopen it with more details.

Thank you very much vor using GPX Animator!
