### ISSUE TITLE
run gradlew.bat timeout error

### ISSUE THREAD

**Issue by jenny59** [gpx-animator/gpx-animator#420]
Hi
I just downloaded the project and installed the gradle.
If I start the "gradlew assemble" now, I get a timeout after a certain time.

the exception:
"Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-7.2-all.zip failed: timeout"

What could be wrong there?

**Comment by McPringle** [comment]
That looks like a local error on your machine/network. Just try it again, maybe your problem was only temporary. If your problem persists, you need to check your internet connection. The build needs internet access to download the dependencies (in this case, the Gradle build tool itself).
