### ISSUE TITLE
API key input

### ISSUE THREAD

**Issue by tittamassi** [gpx-animator/gpx-animator#427]
hi I saw this as been treated in the FAQ, but still I don't understand... should I write the entire URL of the map provider, included the API, in the background map field? I tried but still the error message appear
thank you

**Comment by McPringle** [comment]
Yes, you need to provide the complete URL including placeholders for zoom and x/y coordinates. Example for a link with placeholders (not working, just for explanation):

https://my.tile.server/{zoom}/{x}/{y}.png?API_KEY=12345

That is needed because all the URLs are so different, specially where and how to define the API key, that there is actually no other general solution.

Sorry for my late answer, I was extremely busy and I do GPX Animator in my rare spare time only.

If you still have problems, please reopen this issue and provide the saved configuration (make sure not to post the API key on GitHub).

**Comment by tittamassi** [comment]
Thank you,  I really don’t understand the entire process. I want to animate a gpx of a New Zealand cycling trip:

Which map I have to choose?

Where I find the URL with zoom, X/Y and in which field I have to enter these data?

API key: can I use and API key I can generate via a whatever app I can find online?

Sorry for these very basic and maybe stupid questions.

Enrico

 

Da: Marcus Fihlon ***@***.***> 
Inviato: sabato 17 dicembre 2022 19:33
A: gpx-animator/gpx-animator ***@***.***>
Cc: tittamassi ***@***.***>; Author ***@***.***>
Oggetto: Re: [gpx-animator/gpx-animator] API key input (Issue #427)

 

Yes, you need to provide the complete URL including placeholders for zoom and x/y coordinates. Example for a link with placeholders (not working, just for explanation):

https://my.tile.server/{zoom}/{x}/{y}.png?API_KEY=12345 <https://my.tile.server/%7Bzoom%7D/%7Bx%7D/%7By%7D.png?API_KEY=12345> 

That is needed because all the URLs are so different, specially where and how to define the API key, that there is actually no other general solution.

Sorry for my late answer, I was extremely busy and I do GPX Animator in my rare spare time only.

If you still have problems, please reopen this issue and provide the saved configuration (make sure not to post the API key on GitHub).

**Comment by McPringle** [comment]
> Which map I have to choose?

For New Zealand you can for example choose any map with world wide data. These maps are prefixed with "World". My personal favorites are Skobbler and OpenStreetMap.

Of course, you can check the lists for specialized maps for New Zealand. The country specific maps are prefixed with their 2-digit country code.

> Where I find the URL with zoom, X/Y and in which field I have to enter these data?

Either select a map from the list or enter the URL directly in the background map field. If a map required an API key, the map provider wants you to register (and maybe pay) for their service. You'll get the correct URL from them.

> API key: can I use and API key I can generate via a whatever app I can find online?

To get an API for a special map service, usually you have to register (and maybe pay) to get it. That is the reason for API keys: Provide a service for paying customers.

**Comment by McPringle** [comment]
Handling API keys will be a bit easier in GPX Animator v1.8. There will be a separate text field to enter the API key, so there is no need to enter the URL manually (as long, as the map provider is listed in the background map drop-down box).
