### ISSUE TITLE
Stamen Toner Map

### ISSUE THREAD

**Issue by DGrv** [gpx-animator/gpx-animator#432]
Hi,

Great works, I love it.
I just propose to add a new map and I guess others can also be suggested. Did not find any issues on this so I create a new one.

The Stamen Toner from OSM : https://stamen-tiles-{switch:a,b,c,d}.a.ssl.fastly.net/toner/{zoom}/{x}/{y}.png

Thanks

**Comment by McPringle** [comment]
Hi @DGrv

Thank you very much for your suggestion. GPX Animator itself has no maps or a map directory. A list of maps is downloaded from OpenStreetMap itself. To add a map to GPX Animator, you need to add it to the list of maps at OSM: https://josm.openstreetmap.de/wiki/Maps

After your map was added, go to GPX Animator and select "File > Download Map Updates".
