### ISSUE TITLE
Map zoom higher than default does not work

### ISSUE THREAD

**Issue by cyklotyk** [gpx-animator/gpx-animator#466]
If you try zoom map to any value higher then default calculated (with or without viewport set) rendered view does not follow track.

![image](https://user-images.githubusercontent.com/92172150/206433199-893220d8-a046-4ca4-8726-a6aa78aa387f.png)

**Comment by McPringle** [comment]
If someone searches the issue list and find this question, I would like to add some information to it: If you want a moving map (view follows track), you need to specify or select the viewport size.
