### ISSUE TITLE
EXIF Timezone parsing

### ISSUE THREAD

**Issue by wietze** [gpx-animator/gpx-animator#472]
Before I open a pull request, I'm just trying to understand if I'm missing something or not.

The following lines in PhotoPlugin.java parses the variable `dateTimeString`:
https://github.com/gpx-animator/gpx-animator/blob/master/src/main/java/app/gpx_animator/core/renderer/plugins/PhotoPlugin.java#L161-L162
 
`dateTimeString` [gets](https://github.com/drewnoakes/metadata-extractor/search?q=TAG_TIME_ZONE_ORIGINAL) the timezone from EXIF attribute 0x9011. This field [maps](https://exiftool.org/TagNames/EXIF.html) to OffsetTimeOriginal, which [should](https://en.wikipedia.org/wiki/Exif#Time_Tags) be formatted as a 6-character string formatted as `±HH:MM`.

As can be seen from the highlighted line in PhotoPlugin.java, a single `x` in the `DateTimeFormatter.ofPattern` statement is used to parse the timestamp. The Java docs for DateTimeFormatter [say](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html):
> **Offset X and x**: This formats the offset based on the number of pattern letters. One letter outputs just the hour, such as '+01', unless the minute is non-zero in which case the minute is also output, such as '+0130'. Two letters outputs the hour and minute, without a colon, such as '+0130'. Three letters outputs the hour and minute, with a colon, such as '+01:30'.

As such, `dateTimeString` will be of format `±HH:MM` whereas DateTimeFormatter will try to parse it as `±HH`. 
As a result, that statement is always generating an exception for me (`Text '2023:01:01 01:23:45 +00:00' could not be parsed, unparsed text found at index 23`), meaning the photo's time will never be parsed. 

This behaviour can be quickly replicated using [this online parser](https://javadevtools.com/datetimeformatterparse), using text `2023:01:01 01:23:45 +00:00` and format `yyyy:MM:dd HH:mm:ss x`.

I cloned the repo, changed the `x` in the highlighted line to `xxx`, after which my pictures were successfully parsed and added to the output video.

What I don't understand is how the current code has worked for anyone before, as from what I can see from the git commit history the DateTimeFormatter pattern for timezone has always been `x`, and the EXIF format hasn't changed either.

**Comment by McPringle** [comment]
The offset *should* be formatted using a 6-character string. In my case I have photos which just contain "+02". It looks like it depends on the camera or, in case of a smartphone, the software.

To compensate incorrect implementations by the camera manufacturer, we should extract the parsing to a separate method where we try different patterns, like `xxx`, `xx`, `x`. This will hopefully make every photo work with GPX Animator.

**Comment by McPringle** [comment]
Thank you very much @ky0n!
@wietze: The fix will be part of the next bug fix release v1.8.1, which will be released very soon.

**Comment by wietze** [comment]
Great work, thanks for fixing.
