### ISSUE TITLE
Background Map - Add new map

### ISSUE THREAD

**Issue by Dvorak-Stepan** [gpx-animator/gpx-animator#487]
Please, add new background map: https://en.mapy.cz/turisticka

**Comment by McPringle** [comment]
GPX Animator has no own map database. It will download the maps from the [JOSM project at OpenStreetMap](https://josm.openstreetmap.de/wiki/Maps). Add your map(s) there and GPX Animator will pick them up the next time you download map updates (from the *File* menu). Please check the license(s) of the map(s) you add so there will be no copyright infringement. Details can be found here: https://josm.openstreetmap.de/wiki/Maps

You can use any TMS provider at any time by just pasting the map URL containing placeholders in the background map field. To get the URL, consult the documentation of your map provider. Example: `https://{switch:a,b,c}.tile.openstreetmap.org/{zoom}/{x}/{y}.png`

**Comment by McPringle** [comment]
A quick glance at the *Mapy.cz* website and the inspector of my browser showed me this:

![grafik](https://user-images.githubusercontent.com/1254039/220734536-42026efa-1eb3-4adb-8098-7af45de8cafb.png)

As you can see, a lot of images are loaded: The map. Each file has three numbers in it. The first looks like the zoom level (you can see it changing when zooming in and out). The second and third look like the coordinates (you can see it changing when moving around).

Just copy the URL and replace the numbers with the placeholders should work just fine: https://mapserver.mapy.cz/base-en/{zoom}-{x}-{y}

Paste this in the background map field and enjoy the result. Of course, it would still be nice if you add it to the OSM website mentioned above so all other users are able to select it from the drop down list.
