### ISSUE TITLE
The portrait photos are displayed bottom up (Upside down)

### ISSUE THREAD

**Issue by peterherman** [gpx-animator/gpx-animator#489]
When using a photo folder with existing photos, the portrait photos are displayed bottom up (Upside down). The landscape photos are displayed correctly.

**Comment by McPringle** [comment]
Thank you very much for your report. To properly reproduce the problem, I need the following data:

- Your operating system and version
- The version number of GPX Animator (Help > About)
- The configuration of GPX Animator (File > Save as)
- The GPX file(s) used
- Example photo(s)

Please zip the files and add them to this issue. If you want to keep it private, you can send it as email to support@gpx-animator.app (please add "issue-489" to the subject line).

**Comment by peterherman** [comment]
Windows 11 Home Version 10.0.22621 Build 22621
GPX Animator 1.8.0
[Issue.zip](https://github.com/gpx-animator/gpx-animator/files/10812564/Issue.zip)

**Comment by McPringle** [comment]
Perfect, I'll take a look at it later today.

**Comment by McPringle** [comment]
Thank you very much for your bug report and the example files. We were able to reproduce the problem and implemented a fix. A new release will be published soon. If you used the installer to install GPX Animator, it will check for a new version at application start and pick it up automatically when available.

**Comment by peterherman** [comment]
Is there already a BETA version 1.81? I would like to test it already.

**Comment by McPringle** [comment]
No, there is no beta version available. If you have software developer knowledge, you can compile it yourself from the source code. Otherwise you have to wait for the next release, which is a bug fix release only and will be released quite soon.

**Comment by peterherman** [comment]
Thanks...
