### ISSUE TITLE
Idea: Commandline support for sending config XML to execute

### ISSUE THREAD

**Issue by poorlymac** [gpx-animator/gpx-animator#546]
Hi,

In the GUI you can saver and load the configuration XML, it would ease inter application integration if that XML could be sent on the commandline. e.g. java -jar gpx-animator.jar --run xyz.xml

CHEERS
Paul

**Comment by poorlymac** [comment]
PR created !

**Comment by McPringle** [comment]
This is a duplicate of #325 
Thank you very much for your PR!
