### ISSUE TITLE
Format error when reading date and time

### ISSUE THREAD

**Issue by Rumbah2** [gpx-animator/gpx-animator#590]
Hi,

i got an gpx file out of the bike app I'm using (Bikecomputer Pro). When trying to get a preview after loading the file in GPX Animator 1.8.2 in Windows I get:

Formatfehler beim Lesen von Datum und Uhrzeit: "2023-10-19T08:48:05+02:00" .

The file begins with:
```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1" creator="BikeComputer Pro 8.10.0 Google Play" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/gpx/1/1/gpx.xsd" xmlns="http://www.topografix.com/GPX/1/1" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gpx="http://www.topografix.com/GPX/1/1">
<metadata>
<time>2023-10-19T08:48:05+02:00
</time>
</metadata>
<trk>
<name>Morgenfahrt</name>
<trkseg>
<trkpt lat="52.335873" lon="9.379706">
<ele>92</ele>
<time>2023-10-19T08:48:18+02:00</time>
</trkpt>
```

If I delete the metadata tag including the time it works. I don't know if this tag is standard but in this case it's the time I started the recording in the garage without a gps fix.

I don't know if it's worth a fix as it's very easy to fix the file on my side.

I attached the whole file.
[Morgenfahrt lang_2023_10_19_08_48_05.zip](https://github.com/gpx-animator/gpx-animator/files/13043143/Morgenfahrt.lang_2023_10_19_08_48_05.zip)

**Comment by McPringle** [comment]
Thank you very much for reporting this issue, @Rumbah2. Providing your GPX file helped me a lot in tracking down your problem. It looks like there is a bug in the software of your *Bikecomputer Pro*. If you open your GPX file in a text editor you can spot it in line 4. There is the time, this ride started:

```
<time>2023-10-19T08:48:05+02:00
</time>
```

If you look closely, there is a newline after the timezone identifiert. That should not be there and results in the actual problem.

Even if it is a bug in the software of your device, I'll make GPX Animator more resilient so it will ignore this newline there.
