### ISSUE TITLE
Custom Information for CLI

### ISSUE THREAD

**Issue by robinalexandre** [gpx-animator/gpx-animator#592]
Hello,

Thank you for this app.
When using the CLI with --information, we got : 16:38:45.736 [main] ERROR app.gpx_animator.Main - Missing implementation of command line option 'INFORMATION'. Please report to support.

It seems that the information parameter has been set only for GUI.

#409

**Comment by McPringle** [comment]
Thank you very much @robinalexandre for reporting this bug. @ky0n was so kind to create a fix with PR #601 to solve this problem. It will be part of the next release v1.9.

**Comment by haemi** [comment]
when and where can v1.9 be downloaded? 🙂

**Comment by olets** [comment]
Can we reopen this, to aid findability?
