### ISSUE TITLE
Sometimes the photo animation does not start at the correct map point

### ISSUE THREAD

**Issue by McPringle** [gpx-animator/gpx-animator#644]
Today I created a new video with the actual source from the master branch. Sometimes the photo animation does not start at the correct map point. The animation of the first two photos start way off, the start point of the animation of the last two photos seem to be okay.

Here is a screenshot from the video where the photo animation starts in the top left, but you can see the map point is actually on the bottom right:

![grafik](https://github.com/gpx-animator/gpx-animator/assets/1254039/d9aa0cfb-3d83-4658-af58-6dcf3f0f337e)

The same video, a little bit later, the animation of another photo starts correctly at the actual map point:

![grafik](https://github.com/gpx-animator/gpx-animator/assets/1254039/f9080fdc-43fd-4dce-a572-6aba5695709b)

Here are all relevant files to reproduce: [activity_13085743118.zip](https://github.com/gpx-animator/gpx-animator/files/13753278/activity_13085743118.zip)

@ky0n: Maybe you find some time to have a look at the calculation of the start point? There's no rush at the moment, Xmas comes first!

**Comment by McPringle** [comment]
I can confirm that it works flawless, now. Thank you very much!

**Comment by ky0n** [comment]
great, thanks. Now I have more gpx files for testing.
