### ISSUE TITLE
chosen icon file HUGE!

### ISSUE THREAD

**Issue by csjjpm** [gpx-animator/gpx-animator#744]
Hi, I make a small transparent icon png 40x50 pixels but when rendered it is massive and blurred.  How do I keep it as the original size?

Thanks

**Comment by csjjpm** [comment]
actually may be a image conversion issue

**Comment by McPringle** [comment]
GPX Animator draws the image pixel by pixel.

**Comment by csjjpm** [comment]
The tool I'd used to make the png transparent inflated the size of the image!  Tried something else now.  Thanks
