### ISSUE TITLE
Individual track speed

### ISSUE THREAD

**Issue by csjjpm** [gpx-animator/gpx-animator#745]
Hi,
I currently have two tracks in my animation.  The first is for s ship but it goes very fast and the second is for a train which is going very slowly.  How do I set the speed for the icon to move on each track?

I generated the GPX files online so I do not know about the additional codes required in the GPX files.

Thanks
Paul

**Comment by csjjpm** [comment]
I realise this will work if I put a time entry in each line.  What software can I do this with so I get a constant/specific speed?  Thanks

      <trkpt lon="-6.1861384017725" lat="53.345574784343">
        <time>2024-09-23T14:21:50Z</time>
      </trkpt>
      <trkpt lon="-6.1830425356967" lat="53.345522045791">
        <time>2024-09-23T14:22:10Z</time>
      </trkpt>

**Comment by McPringle** [comment]
If your GPX file has no date/time information or you want to override it, you can specify a time interval per GPX file instead:
![image](https://github.com/user-attachments/assets/1c02ca8a-6cb3-4b79-b9c8-6be56f981faf)
