### ISSUE TITLE
Problems  with '--pre-draw-track' option

### ISSUE THREAD

**Issue by cyklotyk** [gpx-animator/gpx-animator#775]
When putting --pre-draw-track true on command line somwere in the middle you get 

16:14:48.545 [main] ERROR app.gpx_animator.Main - unrecognised option 'true'

Same with '1' 'True' 'Yes' and 'yes' ;-)

The only way to use this option is to put it as last option in command line

java -jar "C:\Program Files\gpx-animator\gpx-animator-1.8.0-all.jar" --input %1.gpx --output %1.mp4  --pre-draw-track

Works perfectly!

**Comment by McPringle** [comment]
I decided to make GPX Animator more resiliant, so it is able to accept `true` and `false` for clearer CLI parameters.

**Comment by McPringle** [comment]
Done with commit [00346e9](https://github.com/gpx-animator/gpx-animator/commit/00346e9ab89aaddb5322deb9e952751c1fbb30c0).
